### ISSUE TITLE
players creating multiple islands

### ISSUE THREAD

**Issue by BloodEko** [Iridium-Development/IridiumTeams#4]
https://github.com/Iridium-Development/IridiumTeams/blob/master/src/main/java/com/iridium/iridiumteams/commands/CreateCommand.java#L35

Hi! I just noticed an issue when creating islands, which results in players having multiple islands.
Shouldn't that check be before line 22? As otherwise there is no check, when no name is specified.

**Comment by PeachesMLG** [comment]
Nice spot, fixed in https://github.com/Iridium-Development/IridiumTeams/commit/b4434dfa376aba9c95b94cbb54d7dcdbc54c7292
